name: mapio
channels:
  - conda-forge
  - defaults
  - digitalglobe
  - ioos
dependencies:
  - affine=2.2.0
  - appnope=0.1.0
  - asn1crypto=0.24.0
  - attrs=18.1.0
  - backcall=0.1.0
  - beautifulsoup4=4.6.0
  - blas=1.1
  - boto3=1.7.15
  - botocore=1.10.15
  - ca-certificates=2018.4.16
  - cartopy=0.16.0
  - certifi=2018.4.16
  - cffi=1.11.5
  - chardet=3.0.4
  - click=6.7
  - click-plugins=1.0.3
  - cligj=0.4.0
  - coverage=4.5.1
  - cryptography=2.2.1
  - curl=7.59.0
  - cycler=0.10.0
  - decorator=4.3.0
  - docutils=0.14
  - et_xmlfile=1.0.1
  - expat=2.2.5
  - fiona=1.7.11
  - freetype=2.6.3
  - freexl=1.0.5
  - future=0.16.0
  - gdal=2.1.4
  - geos=3.6.2
  - geotiff=1.4.2
  - giflib=5.1.4
  - h5py=2.7.1
  - hdf4=4.2.13
  - hdf5=1.10.1
  - icu=58.2
  - idna=2.6
  - impactutils=0.8.3
  - ipython=6.3.1
  - ipython_genutils=0.2.0
  - jdcal=1.4
  - jedi=0.12.0
  - jmespath=0.9.3
  - jpeg=9b
  - json-c=0.12.1
  - kealib=1.4.7
  - krb5=1.14.6
  - libcomcat=1.2.3
  - libdap4=3.18.3
  - libffi=3.2.1
  - libgdal=2.1.4
  - libgfortran=3.0.0
  - libiconv=1.15
  - libnetcdf=4.4.1.1
  - libpng=1.6.34
  - libpq=9.6.3
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lxml=4.2.1
  - matplotlib=2.0.0rc2
  - more-itertools=4.1.0
  - munch=2.3.2
  - ncurses=5.9
  - numpy=1.12.1
  - obspy=1.1.0
  - olefile=0.45.1
  - openblas=0.2.20
  - openjpeg=2.1.2
  - openpyxl=2.5.3
  - openssl=1.0.2o
  - owslib=0.16.0
  - pandas=0.22.0
  - paramiko=2.4.1
  - parso=0.2.0
  - pcre=8.39
  - pexpect=4.5.0
  - pickleshare=0.7.4
  - pillow=4.0.0
  - pip=9.0.3
  - pluggy=0.6.0
  - proj4=4.9.3
  - prompt_toolkit=1.0.15
  - ptyprocess=0.5.2
  - py=1.5.3
  - pyasn1=0.4.2
  - pycparser=2.18
  - pycrypto=2.6.1
  - pyepsg=0.3.2
  - pygments=2.2.0
  - pynacl=1.1.2
  - pyopenssl=17.5.0
  - pyparsing=2.2.0
  - pyproj=1.9.5.1
  - pyshp=1.2.12
  - pysocks=1.6.8
  - pytest=3.5.1
  - pytest-cov=2.5.1
  - python=3.6.5
  - python-dateutil=2.7.2
  - pytz=2018.4
  - rasterio=0.36.0
  - readline=7.0
  - requests=2.18.4
  - s3transfer=0.1.13
  - scipy=1.1.0
  - setuptools=39.1.0
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - six=1.11.0
  - snuggs=1.4.1
  - sqlalchemy=1.2.7
  - sqlite=3.20.1
  - tk=8.6.7
  - tornado=5.0.2
  - traitlets=4.3.2
  - urllib3=1.22
  - wcwidth=0.1.7
  - wheel=0.31.0
  - xerces-c=3.2.0
  - xlrd=1.1.0
  - xlsxwriter=1.0.4
  - xlwt=1.3.0
  - xz=5.2.3
  - zlib=1.2.11
  - bcrypt=3.1.4
