name: mapio
channels:
- conda-forge
- defaults
- ioos
dependencies:
- affine=2.1.0
- asn1crypto=0.22.0
- attrs=17.4.0
- backports=1.0
- backports.functools_lru_cache=1.4
- beautifulsoup4=4.6.0
- blas=1.1
- boto3=1.5.23
- botocore=1.8.38
- ca-certificates=2017.11.5
- cartopy=0.15.1
- certifi=2017.11.5
- cffi=1.11.2
- chardet=3.0.4
- click=6.7
- click-plugins=1.0.3
- cligj=0.4.0
- coverage=4.4.2
- cryptography=2.1.4
- curl=7.55.1
- cycler=0.10.0
- dbus=1.10.22
- decorator=4.1.2
- docutils=0.14
- expat=2.2.5
- fiona=1.7.11
- fontconfig=2.12.6
- freetype=2.8.1
- freexl=1.0.4
- gdal=2.1.4
- geos=3.6.2
- geotiff=1.4.2
- gettext=0.19.8.1
- giflib=5.1.4
- glib=2.55.0
- gst-plugins-base=1.8.0
- gstreamer=1.8.0
- h5py=2.7.1
- hdf4=4.2.13
- hdf5=1.10.1
- icu=58.2
- idna=2.6
- ipython=6.2.1
- ipython_genutils=0.2.0
- jedi=0.11.1
- jmespath=0.9.3
- jpeg=9b
- json-c=0.12.1
- kealib=1.4.7
- krb5=1.14.2
- libdap4=3.18.3
- libffi=3.2.1
- libgdal=2.1.4
- libiconv=1.15
- libnetcdf=4.4.1.1
- libpng=1.6.34
- libpq=9.6.3
- libspatialite=4.3.0a
- libssh2=1.8.0
- libtiff=4.0.9
- libxcb=1.12
- libxml2=2.9.7
- libxslt=1.1.32
- lxml=4.1.1
- matplotlib=2.1.2
- munch=2.2.0
- ncurses=5.9
- numpy=1.14.0
- olefile=0.44
- openblas=0.2.20
- openjpeg=2.1.2
- openssl=1.0.2n
- owslib=0.16.0
- pandas=0.22.0
- paramiko=2.3.1
- parso=0.1.1
- pcre=8.39
- pexpect=4.3.1
- pickleshare=0.7.4
- pillow=5.0.0
- pip=9.0.1
- pluggy=0.6.0
- proj4=4.9.3
- prompt_toolkit=1.0.15
- psutil=5.4.0
- ptyprocess=0.5.2
- py=1.5.2
- pyasn1=0.4.2
- pycparser=2.18
- pycrypto=2.6.1
- pyepsg=0.3.2
- pygments=2.2.0
- pynacl=1.1.2
- pyopenssl=17.4.0
- pyparsing=2.2.0
- pyproj=1.9.5.1
- pyqt=5.6.0
- pyshp=1.2.12
- pysocks=1.6.8
- pytest=3.4.0
- pytest-cov=2.5.1
- python=3.5.4
- python-dateutil=2.6.1
- pytz=2017.3
- qt=5.6.2
- rasterio=0.36.0
- readline=7.0
- requests=2.18.4
- s3transfer=0.1.12
- scipy=1.0.0
- setuptools=38.4.0
- shapely=1.6.4
- simplegeneric=0.8.1
- sip=4.18
- six=1.11.0
- snuggs=1.4.1
- sqlite=3.20.1
- tk=8.6.7
- tornado=4.5.3
- traitlets=4.3.2
- urllib3=1.22
- wcwidth=0.1.7
- wheel=0.30.0
- xerces-c=3.2.0
- xorg-libxau=1.0.8
- xorg-libxdmcp=1.1.2
- xz=5.2.3
- zlib=1.2.11
- bcrypt=3.1.4
- libgcc-ng=7.2.0
- libgfortran=3.0.0
- util-linux=2.21
- pip:
  - backports.functools-lru-cache==1.4
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.15
  - ./libcomcat.zip
  - ./impact.zip

